In [1]:

from pathlib import Path
from timetoalign import ContinuousLogicalTimeline, DiscreteLogicalTimeline
from timetoalign.loader.score.music21 import Music21Loader
from timetoalign.loader.score.partitura import PartituraLoader
from timetoalign.loader.score.tsv import TSVLoader

DATA_DIR = Path(".").resolve().parents[1] / "tests" / "data" / "midi" / "score"
assert DATA_DIR.is_dir(), f"Data dir not found: {DATA_DIR}"
MS3_DIR = DATA_DIR / "ms3"
score_midi_dir = DATA_DIR / "score"
chopin_tsv_notes = MS3_DIR / "chopin_op10_no3.notes.tsv"
chopin_xml = DATA_DIR / "chopin_op10_no3.musicxml"

In [2]:
l1 = TSVLoader()
l1.load(chopin_tsv_notes)
tsv_bundle = l1.bundle

l2 = PartituraLoader()
l2.load(chopin_xml)
pt_bundle = l2.bundle

l3 = Music21Loader()
l3.load(chopin_xml)
m21_bundle = l3.bundle

tsv_df = tsv_bundle.notes.to_dataframe()
pt_df = pt_bundle.notes.to_dataframe()
m21_df = m21_bundle.notes.to_dataframe()

tsv_notes = len(tsv_df[tsv_df["event_type"] == "Note"])
pt_notes = len(pt_df[pt_df["event_type"] == "Note"])
m21_notes = len(m21_df[m21_df["event_type"] == "Note"])

assert tsv_notes == 498
assert pt_notes == 498
assert m21_notes == 498

/home/laser/miniconda3/envs/timetoalign/lib/python3.11/site-packages/partitura/directions.py:514: UserWarning: error parsing "Lento, ma non troppo" (AttributeError)
  warnings.warn('error parsing "{}" ({})'.format(string, type(e).__name__))
/home/laser/miniconda3/envs/timetoalign/lib/python3.11/site-packages/partitura/directions.py:514: UserWarning: error parsing "cresc." (AttributeError)
  warnings.warn('error parsing "{}" ({})'.format(string, type(e).__name__))
/home/laser/miniconda3/envs/timetoalign/lib/python3.11/site-packages/partitura/directions.py:514: UserWarning: error parsing "ritenuto" (AttributeError)
  warnings.warn('error parsing "{}" ({})'.format(string, type(e).__name__))
/home/laser/miniconda3/envs/timetoalign/lib/python3.11/site-packages/partitura/directions.py:514: UserWarning: error parsing "a tempo" (AttributeError)
  warnings.warn('error parsing "{}" ({})'.format(string, type(e).__name__))

In [3]:
all_column_metadata = {field.name: field.metadata for field in tsv_bundle.notes.table.schema}

print(all_column_metadata)

{'id': None, 'name': None, 'temporal_type': None, 'event_type': None, 'start': {b'unit': b'quarters'}, 'end': {b'unit': b'quarters'}, 'duration': {b'unit': b'quarters'}, 'duration_float': None, 'mc': {b'number_type': b'int64'}, 'mn': None, 'mc_onset': {b'number_type': b'fraction'}, 'mn_onset': {b'number_type': b'fraction'}, 'midi_pitch': None, 'spelled_pitch': None, 'tpc': {b'number_type': b'int64', b'unit': b'fifths'}, 'octave': {b'number_type': b'int64'}, 'velocity': {b'number_type': b'int64'}, 'tied': None, 'gracenote': None, 'chord_id': None, 'voice': {b'number_type': b'int64'}, 'staff': {b'number_type': b'int64'}, 'part_id': None}

In [4]:
tsv_df

,id,name,temporal_type,event_type,start,end,duration,duration_float,mc,mn,...,spelled_pitch,tpc,octave,velocity,tied,gracenote,chord_id,voice,staff,part_id
0,note_0.0_0,B3,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.50,1,1,...,"{'gpc_int': 6, 'gpc_str': 'B', 'acc': 0, 'spc_...",5,3,64,0,NaN,0,1,1,P1
1,note_0.5_1,E2,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.25,2,2,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,2,64,0,NaN,14,1,2,P1
2,note_0.5_2,E2,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,2,2,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,2,64,0,NaN,20,3,2,P1
3,note_0.5_3,G#3,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.25,2,2,...,"{'gpc_int': 4, 'gpc_str': 'G', 'acc': 1, 'spc_...",8,3,64,0,NaN,6,3,1,P1
4,note_0.5_4,E4,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.50,2,2,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,4,64,0,NaN,1,1,1,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,note_40.5_493,E2,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,2,64,-1,NaN,470,2,2,P1
494,note_40.5_494,B2,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 6, 'gpc_str': 'B', 'acc': 0, 'spc_...",5,2,64,-1,NaN,469,1,2,P1
495,note_40.5_495,E3,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,3,64,0,NaN,469,1,2,P1
496,note_40.5_496,G#3,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 4, 'gpc_str': 'G', 'acc': 1, 'spc_...",8,3,64,0,NaN,468,3,1,P1
497,note_40.5_497,E4,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,4,64,0,NaN,467,1,1,P1

In [5]:
pt_df

,id,name,temporal_type,event_type,start,end,duration,duration_float,mc,mn,...,spelled_pitch,tpc,octave,velocity,tied,gracenote,chord_id,voice,staff,part_id
0,n0,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.50,1,1,...,"{'gpc_int': 6, 'gpc_str': 'B', 'acc': 0, 'spc_...",5,3,64,0,NaN,NaN,1,1,P1
1,n1,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.50,2,2,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,4,64,0,NaN,NaN,1,1,P1
2,n2,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.25,2,2,...,"{'gpc_int': 4, 'gpc_str': 'G', 'acc': 1, 'spc_...",8,3,64,0,NaN,NaN,3,1,P1
3,n3,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.25,2,2,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,2,64,0,NaN,NaN,4,2,P1
4,n4,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,2,2,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,2,64,0,NaN,NaN,7,2,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,n493,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,4,64,0,NaN,NaN,1,1,P1
494,n494,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 4, 'gpc_str': 'G', 'acc': 1, 'spc_...",8,3,64,0,NaN,NaN,3,1,P1
495,n495,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,3,64,0,NaN,NaN,4,2,P1
496,n496,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 6, 'gpc_str': 'B', 'acc': 0, 'spc_...",5,2,64,0,NaN,NaN,4,2,P1
497,n497,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,2,64,0,NaN,NaN,5,2,P1

In [6]:
m21_df

,id,name,temporal_type,event_type,start,end,duration,duration_float,mc,mn,...,spelled_pitch,tpc,octave,velocity,tied,gracenote,chord_id,voice,staff,part_id
0,139989816053776,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.50,1,1,...,"{'gpc_int': 6, 'gpc_str': 'B', 'acc': 0, 'spc_...",5,3,64,0,NaN,NaN,NaN,NaN,Chopin_op10_no3
1,139989915674064,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.50,2,2,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,4,64,0,NaN,NaN,NaN,NaN,Chopin_op10_no3
2,139989747150736,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.25,2,2,...,"{'gpc_int': 4, 'gpc_str': 'G', 'acc': 1, 'spc_...",8,3,64,0,NaN,NaN,NaN,NaN,Chopin_op10_no3
3,139989747205136,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",0.25,2,2,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,2,64,0,NaN,NaN,NaN,NaN,Chopin_op10_no3
4,139989747209680,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,2,2,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,2,64,0,NaN,NaN,NaN,NaN,Chopin_op10_no3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,139989744338000,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,4,64,0,NaN,NaN,NaN,NaN,Chopin_op10_no3
494,139989744340880,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 4, 'gpc_str': 'G', 'acc': 1, 'spc_...",8,3,64,0,NaN,NaN,NaN,NaN,Chopin_op10_no3
495,139989744341968,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,3,64,0,NaN,NaN,NaN,NaN,Chopin_op10_no3
496,139989744342992,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 6, 'gpc_str': 'B', 'acc': 0, 'spc_...",5,2,64,0,NaN,1.399897e+14,NaN,NaN,Chopin_op10_no3
497,139989744344848,,interval,Note,"{'value': None, 'numerator': None, 'denominato...",None,"{'value': None, 'numerator': None, 'denominato...",1.00,22,22,...,"{'gpc_int': 2, 'gpc_str': 'E', 'acc': 0, 'spc_...",4,2,64,0,NaN,NaN,NaN,NaN,Chopin_op10_no3

In [7]:
T = ContinuousLogicalTimeline()
U = DiscreteLogicalTimeline()
T

ContinuousLogicalTimeline(id='tl:1', length=0, unit=quarters, events=0, children=0)

In [10]:

for store in tsv_bundle:
    T.add_child(ContinuousLogicalTimeline.from_event_store(store), 0)
T

ContinuousLogicalTimeline(id='tl:1', length=0, unit=quarters, events=0, children=4)

In [14]:
T.events.table.to_pandas()

,id,name,temporal_type,event_type,start,end,duration
0,tl:4,tl:4,interval,Segment,"{'value': 0.0, 'numerator': 0, 'denominator': 1}","{'value': 0.0, 'numerator': 0, 'denominator': 1}","{'value': 0.0, 'numerator': 0, 'denominator': 1}"
1,tl:5,tl:5,interval,Segment,"{'value': 0.0, 'numerator': 0, 'denominator': 1}","{'value': 0.0, 'numerator': 0, 'denominator': 1}","{'value': 0.0, 'numerator': 0, 'denominator': 1}"
2,tl:6,tl:6,interval,Segment,"{'value': 0.0, 'numerator': 0, 'denominator': 1}","{'value': 0.0, 'numerator': 0, 'denominator': 1}","{'value': 0.0, 'numerator': 0, 'denominator': 1}"
3,tl:7,tl:7,interval,Segment,"{'value': 0.0, 'numerator': 0, 'denominator': 1}","{'value': 0.0, 'numerator': 0, 'denominator': 1}","{'value': 0.0, 'numerator': 0, 'denominator': 1}"